### ISSUE TITLE
Lacks of libgpgme dependency declaration

### ISSUE THREAD

**Issue by FlachyJoe** [saturneric/GpgFrontend#160]
libgpgme is needed to compile else the following error occurs

```
/src/core/typedef/GpgTypedef.h:31:10: fatal error: gpgme.h: Aucun fichier ou dossier de ce type
   31 | #include <gpgme.h>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by saturneric** [comment]
On operating systems currently supported by GpgFrontend, gpgme can be installed via a package manager. Therefore, the build code for gpgme is not included in the project configuration of GpgFrontend.

**Comment by FlachyJoe** [comment]
Hi,
cmake should check for the gpgme package before the build process.

**Comment by saturneric** [comment]
I've already introduced a [cmake script](https://github.com/saturneric/GpgFrontend/blob/main/cmake/FindGpgme.cmake) to do this, but it doesn't work very well. However, due to the complexity of deploying the gpgme library on various platforms, I was hoping that the author of this script would continue to improve it. But my attempts to find any newer versions have failed so far.

**Comment by Doujinx28** [comment]
Well, where it be that script ? Take your time, ofc.

**Comment by saturneric** [comment]
You can find it Here: https://github.com/saturneric/GpgFrontend/blob/main/cmake/FindGpgme.cmake
