### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by liups233** [saturneric/GpgFrontend#42]
Unfortunately, there is no direct binary files for OpenBSD. And for me, to fulfill all the dependencies is quite hard. 
Yeah, I would appreciate if you could consider adding support for OpenBSD...

**Comment by saturneric** [comment]
Hi, adding support for Unix platforms like FreeBSD or OpenBSD is part of my plan which I will be implementing in the near future.

**Comment by saturneric** [comment]
Adapting BSD is more difficult than I thought, as client software, although the source code is cross-platform, this does not mean that all platforms can provide uniform compilation and linking support, especially since third-party libraries are available. I am trying to develop a new generation of GpgFrontend based on Electron, called GpgFrotnend-E. This generation should be able to support the BSD platform.

**Comment by saturneric** [comment]
Done
