### ISSUE TITLE
Windows: GnuPG - Update to current version 2.3.7 (?)

### ISSUE THREAD

**Issue by panther2** [saturneric/GpgFrontend#69]
Hey, I came to know GpgFrontend only by today - and yes, it looks great.

One question, though - I noticed that the current release-zip comes with GnuPG 2.3.6.

So I wonder about your update policy... are you going to bundle the new GnuPG (currenlty 2.3.7) anytime soon?
Or do you stick with the shipped version for some time? 

Thank you.

**Comment by SoftwUser** [comment]
@saturneric 
I second this question - or is there an easy way for Windows users to replace the bundled GnuPG version with the latest one themselves - without losing 'portability'?

**Comment by saturneric** [comment]
> @saturneric 
> 
> I second this question - or is there an easy way for Windows users to replace the bundled GnuPG version with the latest one themselves - without losing 'portability'?

Hi, you can just use the latest GnuPG binary to overwrite the old one. It will work.

**Comment by sergeevabc** [comment]
By moving to QT6 you effectively cut off users from places where they still use Windows 7. Whoa, encryption just became less accessible, what a great move. So what's the last version that works on Windows 7?

**Comment by saturneric** [comment]
Thank you for bringing up your concerns about the compatibility of my software with Windows 7 following the move to QT6. I want to clarify the reasoning behind this decision. The upgrade was primarily motivated by the limitations of Qt5, which does not support OpenSSL3. Additionally, Qt5 has become quite dated, leading to less appealing UI elements and a lack of support for many modern language features and graphical library APIs. The transition to Qt6 was smoother in comparison.

However, I acknowledge that I did not fully consider the implications for Windows 7 users. It's been a long time since I've used this operating system myself, and with my limited personal resources, I can only focus on maintaining one main development branch. My general policy is to phase out support for operating systems that no longer receive security updates. The last version of my software that supports Qt5 is 2.0.10.

I understand this might be inconvenient for some, and I apologize for any issues it may cause. If there is significant demand from Windows 7 users, I am open to providing long-term bug maintenance for the 2.0.x versions. However, this will require some time to find additional help, as my current bandwidth as an individual developer is not sufficient to support two development branches concurrently.

**Comment by sergeevabc** [comment]
@saturneric, I see that QT5 version is back.

However, 2.1.3 QT5 does not work on Windows 7. It seems you compiled it without targeting that OS as a minimum, so it tries to use KERNEL32.dll calls introduced in Windows 8 such as [CreateFile2][1] instead of CreateFileW. It leads to the fatal error.



If I replace that call in `libarchive.dll`, then GPGFrontend launches. 

``` console
$ sfk.exe replace -pat /CreateFile2/CreateFileW/ -dir . -file *.* -yes
[total hits/matching patterns/non-matching patterns]
[003/1/0] libarchive.dll
109 files checked, 1 changed.
```

Some labels look odd, but that's another issue.

![2024-0513-0202 gpgfrontend 216 window](https://github.com/saturneric/GpgFrontend/assets/373718/0041d871-2677-4039-9b92-5229a1b2b473)


[1]: https://www.google.com/search?q=%22CreateFile2%22+%22windows+7%22+site%3Astackoverflow.com
[2]: https://en.wikipedia.org/wiki/SeaMonkey

**Comment by saturneric** [comment]
> @saturneric, I see that QT5 version is back.
> 
> However, 2.1.3 QT5 does not work on Windows 7. It seems you compiled it without targeting that OS as a minimum, so it tries to use KERNEL32.dll calls introduced in Windows 8 such as [CreateFile2](https://www.google.com/search?q=%22CreateFile2%22+%22windows+7%22+site%3Astackoverflow.com) instead of CreateFileW. It leads to the fatal error.
> 
> ![2024-0513-0202 gpgfrontend 216 createfile2 error](https://private-user-images.githubusercontent.com/373718/329886194-ce14518f-0621-4aeb-8128-4ff88a596a69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY4MDgsIm5iZiI6MTcxNTYyNjUwOCwicGF0aCI6Ii8zNzM3MTgvMzI5ODg2MTk0LWNlMTQ1MThmLTA2MjEtNGFlYi04MTI4LTRmZjg4YTU5NmE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGZmNGFhNzliYmQyZTBmYjQxZjQ1MzQ3ZmZiMTNjMjQyMzMwYThiOGUzMmI2MmNkNDkxYWY0NjRkMDg3YjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uhgHP20k8eWxiUdjn_IiOEQeMJ8vzQHd65_C1YMeU8Q)
> 

I use windows server 2019 to build this binary piece. And as you said, its binary env seems to be a little bit too new for windows 7. But the oldest hosted window runner Github can provide is windows server 2019. 

![image](https://github.com/saturneric/GpgFrontend/assets/20257134/1405e136-3b5a-4fe9-876c-d841cfd48f3d)

Maybe we need to find another way to produce the windows 7 suitable one automately.

> If I replace that call in `libarchive.dll`, then GPGFrontend launches.
> 
> ```
> $ sfk.exe replace -pat /CreateFile2/CreateFileW/ -dir . -file *.* -yes
> [total hits/matching patterns/non-matching patterns]
> [003/1/0] libarchive.dll
> 109 files checked, 1 changed.
> ```
> 
> Some labels look odd, but that's another issue.
> 
> ![2024-0513-0202 gpgfrontend 216 window](https://private-user-images.githubusercontent.com/373718/329886112-b233633f-57a8-4b5c-98f2-d2810216b5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY4MDgsIm5iZiI6MTcxNTYyNjUwOCwicGF0aCI6Ii8zNzM3MTgvMzI5ODg2MTEyLWIyMzM2MzNmLTU3YTgtNGI1Yy05OGYyLWQyODEwMjE2YjViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2JiZTVhYzllNWVhZDgyMTRjNmQ4ZDAyOTI2NmI1Yjc4N2VkZTE4MDJiZjFlN2RjZTk4ZmI3YTgxN2ZiNGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D5NKqMJSrS6Q1_6rdtPuIfMbodX4Q9n5afu02GkaRQA)
> 

You can now set the option “Kill all GnuPG daemon ...” at GnuPG Controller  to True, it may solve the `keyboxd.exe` problem.

> Also, some `keyboxd.exe` stays in memory after closing GPGFrontend, which is not expected when we deal with portable apps, but that's another issue too.


And @sergeevabc, could you please copy all these releated info to a new issue? We can track these things properly then.

**Comment by sergeevabc** [comment]
> And @sergeevabc, could you please copy all these releated info to a new issue? We can track these things properly then.

[Okay][1].

[1]: https://github.com/saturneric/GpgFrontend/issues/151
